### ISSUE TITLE
Deployment succeeds but workflow reports failure

### ISSUE THREAD

**Issue by brandiqa** [amondnet/now-deployment#12]
I have a [static website](https://github.com/brandiqa/static-bootstrap-site) am trying to deploy using GitHub actions. I've copied the workflow provided https://github.com/marketplace/actions/zeit-now-deployment.

Despite the deployment being successful, GitHub displays annotations errors:

![annotation-errors](https://snipboard.io/rxEdNQ.jpg)

**Edit**
I have a deadline to complete this project. Hence I'll need to remove the zeit deploy workflow and switch to deployment via Zeit GitHub integration. Here's the deployment GitHub Action for reference:

```yaml
name: Deploy static website

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: amondnet/now-deployment@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          zeit-team-id: team_XXXXXXXXXXX
          now-args: '--prod'
```
