### ISSUE TITLE
Do not want to receive comments from action

### ISSUE THREAD

**Issue by nb5p** [amondnet/now-deployment#14]
Hello, I used this action, it is very convenient to replace now bot. I don't want to receive comments under commit every time I deploy to now. I removed github-token and it can be deployed to now, but ci reports an error. I hope that github-token can be turned into an optional item.

**Comment by amondnet** [comment]
@nb5p Hi, thank you for your good feedback. I will work on it next week.

**Comment by sergeyfilimonov** [comment]
@amondnet same here, I removed GitHub token but every time I get ```##[error]Bad credentials
##[error]Node run failed with exit code 1``` though the app deploys well on Zeit.

**Comment by amondnet** [comment]
@nb5p @sergeyfilimonov 

`github-token` is now optional.

```yaml
- uses: amondnet/now-deployment@v1
  with:
    zeit-token: ${{ secrets.ZEIT_TOKEN }}
```
