### ISSUE TITLE
Can I upload the contents of a folder with pre-built assets?

### ISSUE THREAD

**Issue by NullVoxPopuli** [amondnet/now-deployment#22]
I'd like to manage the build for my app in GH actions. Is this possible with the now action?

**Comment by amondnet** [comment]
Yes it is possible. 
example(angular):
```yaml
name: deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest
    needs: prepare
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.10
      uses: actions/setup-node@v1
      with:
        node-version: 12.10
    - name: npm install, build
      run: |
        npm install
        npx ng build --prod
    - uses: amondnet/now-deployment@v1
      with:
        zeit-token: ${{ secrets.NOW_TOKEN }}
        now-args: '--prod'
        working-directory: ./dist/sample-app
```
