### ISSUE TITLE
Support for Now CLI v17

### ISSUE THREAD

**Issue by honzajavorek** [amondnet/now-deployment#24]
Since version 17 the Now CLI is now interactive by default. It can be worked around using environment variables - https://github.com/zeit/now/pull/3588 Perhaps this action could take these as options and set the variables.

**Comment by amondnet** [comment]
@honzajavorek  v2 released
```yaml
name: deploy website
on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }} # Required
          now-args: '--prod' 
          now-org-id: 'YOUR_ORG' 
          now-project-id: 'YOUR_PROJECT_ID' 
```
