### ISSUE TITLE
Outputs object is always empty

### ISSUE THREAD

**Issue by followbl** [amondnet/now-deployment#25]
Is there anything I'm doing wrong here? I'm having trouble accessing the output from the now-deployment step...found adding the id to the step in the forums, but still no luck. Any assistance if I'm missing something simple is appreciated.

```
name: CI
on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Deploy
        uses: amondnet/now-deployment@v1
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }} # Required
          zeit-team-id: team_123 #Optional
          now-args: "--scope team123 --confirm"
        id: build_zeit

      - name: Cypress Test
        uses: cypress-io/github-action@v1
        with:
          config: baseUrl=${{ steps.build_zeit.outputs.preview-url }}
```
