### ISSUE TITLE
How can I deploy with an assigned domain?

### ISSUE THREAD

**Issue by jackguoAtJogg** [amondnet/now-deployment#30]
I wonder how can I deploy with an assigned domain so it deploys to the same location every time this github action runs.

**Comment by amondnet** [comment]
use [prod](https://zeit.co/docs/now-cli#commands/now/unique-options/prod)
The `--prod` option can be used to create a deployment for a production domain specified in the project dashboard.

Usage Example:
```yml
name: deploy production website
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          zeit-team-id: team_XXXXXXXXXXX #Optional 
          now-args: '--prod' #Optional
          now-org-id: 'example_org_id' #Required
          now-project-id: 'example_project_id' #Required 
          working-directory: ./sub-directory #Optional
```
