### ISSUE TITLE
Team project builds are failing because `now inspect` uses default scope

### ISSUE THREAD

**Issue by Regaddi** [amondnet/now-deployment#50]
Hey :wave:

It would be good to be able to configure the `--scope` flag for `now inspect`.
By default it uses my personal space, but when deploying a team project it should instead search within the team scope.

Example output:
```
$ now inspect https://my-team-project.now.sh/
Now CLI 19.0.1
Error! Failed to find deployment "https://my-team-project.now.sh/" in regaddi

$ now inspect https://my-team-project.now.sh/ --scope my-team
Now CLI 19.0.1
> Fetched deployment "my-team-project.now.sh" in my-team [2s]
...
```

This leads to failing builds, because the team project can't be found within my personal scope.

It used to work with now 18.0.0, but fails with now 19.0.1.

Thanks in advance for your help!

**Comment by amondnet** [comment]
Hi, @Regaddi 
Currently, you can do this through a vercel configuration file. 
https://vercel.com/docs/configuration#project/scope
```json
{
  "github": {
     "enabled": false
  },
  "version" : 2,
  "scope": "my-team"
}
```
I will add this feature to the next version.

**Comment by Regaddi** [comment]
Hey @amondnet,

thanks for your response!
I tested this by adding the scope property to my configuration file, but unfortunately it still doesn't respect the configured scope for the `inspect` step:

![image](https://user-images.githubusercontent.com/1336590/82198905-44677480-98fd-11ea-8715-4ce5700e191c.png)

This is the configuration file:

```json
{
  "version": 2,
  "scope": "my-team",
  "builds": [
    {
      "src": "/packages/dashboard/package.json",
      "use": "@now/next"
    }
  ],
  "routes": [
    {
      "src": "/(.*)",
      "dest": "/packages/dashboard/$1",
      "continue": true
    }
  ]
}

```

Thanks!

**Comment by amondnet** [comment]
hi @Regaddi ,
Fixed in https://github.com/amondnet/vercel-action/pull/5
```yaml
      - uses: vercel-action@v19 //v19.0.1+1
        id: vercel-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID_TEAM_SCOPE }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_TEAM_SCOPE }}
          working-directory: example/team-scope
          scope: ${{ secrets.VERCEL_SCOPE }}
```
