### ISSUE TITLE
Usage with lighthouse CI action

### ISSUE THREAD

**Issue by VladSez** [amondnet/now-deployment#53]
I have a next.js project which uses now-deployment github action and now i want to add lighthouse ci action https://github.com/marketplace/actions/lighthouse-ci-action
The question is can i get preview url from now-deployment action and pass it lighthouse CI action?
Is this a right approach?

this is what i currently have 

![image](https://user-images.githubusercontent.com/16666234/83204455-8c379880-a154-11ea-82c5-17caa7a5b4d3.png)

there is an example in lighthouse ci repo that i was using

![image](https://user-images.githubusercontent.com/16666234/83204130-bfc5f300-a153-11ea-8cbd-36abd01f8291.png)

**Comment by amondnet** [comment]
@VladSez 
This actions has two [outputs](https://github.com/amondnet/now-deployment/blob/93de56fa183962f0109e1b9e0b4b4e7aeca52e7f/action.yml#L34)



https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#steps-context

> `steps.<step id>.outputs.<output name>` : The value of a specific output.


example:
```yaml
steps:
    - id: deploy-step
      use: amondnet/now-deployment
      // your config
    - name: use output
       run: echo ${{ steps.deploy-step.outputs.preview-url }}

```
