### ISSUE TITLE
create preview deployment and control the url name

### ISSUE THREAD

**Issue by esakal** [amondnet/now-deployment#54]
Hello,
Can I run this action and control the name of the preview url? the same as the automatic integration is doing by appending the PR version to the preview url? I want to be able to provide to the action a string that identify versions to append to my domain, so if my domain is `my-domain.now.sh` with the version it will be  `http://my-domain-v1-0-0.now.sh/`

Also, can I prevent the integration on specific branches? so it will work on PRs and not on `master` branch commits?

Can I do that with this action?
Thanks
Eran.

**Comment by amondnet** [comment]
> Can I run this action and control the name of the preview url? the same as the automatic integration is doing by appending the PR version to the preview url? I want to be able to provide to the action a string that identify versions to append to my domain, so if my domain is my-domain.now.sh with the version it will be http://my-domain-v1-0-0.now.sh/

Currently, it can't. It will be possible in the next version.
https://github.com/amondnet/vercel-action/issues/7

> Also, can I prevent the integration on specific branches? so it will work on PRs and not on master branch commits?

https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags

When using the push and pull_request events, you can configure a workflow to run on specific branches or tags. For a pull_request event, only branches and tags on the base are evaluated. If you define only tags or only branches, the workflow won't run for events affecting the undefined Git ref.

```yaml
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on master branch
      - master
      # Push events to branches matching refs/heads/mona/octocat
      - 'mona/octocat'
      # Push events to branches matching refs/heads/releases/10
      - 'releases/**'
    # Sequence of patterns matched against refs/tags
    tags:        
      - v1             # Push events to v1 tag
      - v1.*           # Push events to v1.0, v1.1, and v1.9 tags

```
