### ISSUE TITLE
Add  prod args have an error invalidTagName

### ISSUE THREAD

**Issue by bestony** [amondnet/now-deployment#6]
## Description
if i add `now-args: '--prod'`, it can't pass the deploy ,with error `Error: Invalid tag name "now --prod": Tags may not have any characters that encodeURIComponent encodes.`
![image](https://user-images.githubusercontent.com/13283837/69918376-1fe12280-14ac-11ea-84ad-4d0e8675fc08.png)

## Code
```
name: hexo deploy 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup node
      uses: actions/setup-node@v1.1.0
      with:
        version: 13
    - name: Install
      run: npm install hexo-cli -g && npm install
    - name: Cache
      uses: actions/cache@v1.0.3
      with:
        key: node-cache
        path: node_modules
    - name: Build
      run: hexo g 
    - name: Deploy
      uses: amondnet/now-deployment@v1
      with:
        zeit-token: ${{secrets.NOW_TOKEN}}
        github-token: ${{ secrets.GH_TOKEN }}
        now-args: '--prod'
```
